### ISSUE TITLE
Lamin upload fails due to missing s3fs

### ISSUE THREAD

**Issue by Zethson** [laminlabs/bionty-base#386]
```

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/fsspec/registry.py", line 220, in get_filesystem_class
    register_implementation(protocol, _import_class(bit["class"]))
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/fsspec/registry.py", line 243, in _import_class
    mod = importlib.import_module(mod)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 's3fs'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/bionty/bionty/./scripts/upload_new_ontologies.py", line 55, in <module>
    _upload_ontology_artifacts(
  File "/home/runner/work/bionty/bionty/./scripts/upload_new_ontologies.py", line 26, in _upload_ontology_artifacts
    ln.setup.load(instance, migrate=True)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/lndb/_load_instance.py", line 50, in load
    isettings = InstanceSettings(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/lndb/dev/_settings_instance.py", line 52, in __init__
    self._engine: Engine = sqm.create_engine(self.db)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/lndb/dev/_settings_instance.py", line 130, in db
    return f"sqlite:///{self.storage.cloud_to_local(self._sqlite_file)}"
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/lndb/dev/_storage.py", line 135, in cloud_to_local
    filepath.synchronize(local_filepath)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/lndb/dev/upath.py", line 47, in _synchronize
    if not self.exists():
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/upath/core.py", line 378, in exists
    if not getattr(self._accessor, "exists"):
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/upath/core.py", line 188, in __getattr__
    self._accessor = _accessor = self._default_accessor(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/upath/core.py", line 35, in __init__
    cls = get_filesystem_class(parsed_url.scheme)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/fsspec/registry.py", line 222, in get_filesystem_class
    raise ImportError(bit["err"]) from e
ImportError: Install s3fs to access S3
```

Probably due to @Koncopd recent changes. I'll investigate.

**Comment by Koncopd** [comment]
Hi @Zethson i don't know where it happens but the storage deps were moved to extras. If you need s3fs, you have to install `lamindb[aws]`

**Comment by sunnyosun** [comment]
Tried to specify here https://github.com/laminlabs/bionty/actions/runs/5125259441/jobs/9218717380, but CI still fails for other reasons...

**Comment by Zethson** [comment]
That's actually again laminci being flaky. This is before the script @sunnyosun

**Comment by falexwolf** [comment]
This is the CI setup being flaky. The error tells us that lamindb was never properly setup & imported
```
AttributeError: module 'lamindb' has no attribute 'add'
```

I haven't understood how this happens exactly, but it seems related to using instances with different lamindb versions across different environments. It's clear that this is a bad idea because schemas can differ, and import checks will fail (producing the outcome that lamindb is imported with the warning "not yet configured", which is lost in the botocore logging in this case and we just see the AttributeError)

In particular, the nox & and the base runner environment can differ

I wrote on this here: https://laminlabs.slack.com/archives/C04A0RMA0SC/p1685362315736869

My current solution is to radically refactor CI and get rid of the intransparency caused by the nox installs: to that end, I've refactored CI in lamindb, lndb, lnschema-core & lamin-docs, and sped up build times significantly, and don't run into errors anymore

Happy to do the same for the bionty repo!

**Comment by Zethson** [comment]
Yeah, it would be great if you could do this for Bionty as well, please @falexwolf ! But if you just update the template I can also figure out how to do this myself for Bionty easily enough if you're busy and don't want to do it yourself for every repository.

**Comment by falexwolf** [comment]
I'll do! I haven't yet modified the template because I was still optimizing and gaining experience across repos & use cases - so I'd do a quick fix for the bionty repo and then we can decide together what the new cookie-cutter will be; and probably there should be at least two: one for a schema module & one for a standard python package
